### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by ScreenDream** [vjgegenlicht/VL.LoopTool#1]
I get the following error when trying to install in 5.3.0423:
![image](https://github.com/vjgegenlicht/VL.LoopTool/assets/113698935/b3e4372f-b134-4e82-82ea-4f2b1cb5df95)
Anything special I need to do to make it work?

Thank you, sounds great! :-)

Windows 11 Home.

P.S. I actually have ScreenRecorder already installed.

**Comment by ravel-of** [comment]
Hi. I am having the same Issue today. Last friday during your workshop it was working fine. Windows 10

**Comment by ScreenDream** [comment]
I can report that today I was able to successfully install in 5.3.0423

Thanks!!! :-)

**Comment by ScreenDream** [comment]
Sadly, with latest V4 6.0092 I am back at square one, can't install 0.5.6.1 because of the VL.ScreenRecorder dependency, same as in above screenshot.
If I can be of further assistance, let me know.
Cheers,
Tom

**Comment by vjgegenlicht** [comment]
this is really strange and i still cant replicate it. i have asked others with more experience with nuget publication for help and will report back. 
For me it still work when i add the "-pre" at the end.  `nuget install vl.looptool -pre`   The pre will always be needed, even when looptool is out of preview since vl.screenrecorder is also still in preview. I suspect it has something to do with this.

**Comment by ScreenDream** [comment]
AH!
So maybe mark it as prerelease on Nuget.org too?
I now saw that you have it on Github in the docs, but on Nuget.org it doesn't say prerelease anymore and I didn't investigate further.
I would think that even when only a dependency is -pre, the whole package should be marked as that?
Otherwise you'll probably keep getting those error reports ... ;-)

The examples now work for the first time too, yay!

I now only have the issue left that some of the render windows land outside my monitor and can't be scaled, but that is minor - I guess you use a high-res monitor?

Thank you!
Will investigate the tools finally :-)

Cheers!

Tom

**Comment by vjgegenlicht** [comment]
Thx i will check the default window positions and size for the help patches. I dont really know how to change these settings on nuget.org, if someone can give me a hint there would be helpful. 

I can add an option to allow resizing the renderer window.  To solve the issue you can select the renderer or the looptool inspector via alt+tab and then use win+arrow keys to move the window to your screen. The renderer window size and position can be set in the loopinspector.
